live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#928374"
blue = "#83a5a8"
cyan = "#8ed08c"
green = "#b8cb26"
magenta = "#e386ab"
red = "#fd4934"
white = "#fbcbc2"
yellow = "#fdcd2f"

[colors.cursor]
cursor = "#fbcbc2"
text = "#000000"

[colors.footer_bar]
background = "#fbcbc2"
foreground = "#000000"

[colors.normal]
black = "#000000"
blue = "#458598"
cyan = "#68ad7a"
green = "#98a21a"
magenta = "#a16296"
red = "#d0241d"
white = "#b8a994"
yellow = "#d7a221"

[colors.primary]
background = "#000000"
foreground = "#fbcbc2"

[colors.search.focused_match]
background = "#ffffff"
foreground = "#000000"

[colors.search.matches]
background = "#440040"
foreground = "#ffa0ff"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "#ff0000"
text = "CellBackground"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 9.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "L"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
action = "Copy"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "Y"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = false

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "U"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Plus"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "U"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "B"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "F"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Q"
mode = "Vi|~Search"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
dynamic_title = true
opacity = 0.85
title = "alacritty"

[window.class]
general = "Alacritty"
instance = "alacritty"

[window.dimensions]
columns = 110
lines = 30

[window.padding]
x = 0
y = 0
